### ISSUE TITLE
[Feature] Update metrics spec to be 1.6 compatiable

### ISSUE THREAD

**Issue by Jstein77** [fivetran/dbt_ad_reporting#101]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

dbt-core has a new metric spec as of 1.6. We need to update the metrics in the package to be compatible with the new spec. 

### Describe alternatives you've considered

Remove metrics, or only use the package on dbt versions <1.6

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
This update has been reflected in the latest v1.6.0 release of the ad reporting package! As such, I will close out this issue. Thanks again for contributing to the package @Jstein77!
