### ISSUE TITLE
[Bug] Update semantic model name

### ISSUE THREAD

**Issue by Jstein77** [fivetran/dbt_ad_reporting#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

We released an update to `dbt-semantic-interfaces` that reserves the dunder(__) character as a keyword, and does not allow dunders in semantic model names. The package currently has a semantic model named `ad_reporting__ad_report`. This is causing dbt parse jobs to fail on dbt v1.6.5. 

To fix this bug we need to updated the name of the semantic models to remove dunders.

### Expected behavior

dbt parse should succeed when we remove dunders from the semantic model names.

### dbt Project configurations

vars:
  ad_reporting:
    ad_reporting__account_passthrough_metrics: []
    ad_reporting__campaign_passthrough_metrics: []
    ad_reporting__ad_group_passthrough_metrics: []
    ad_reporting__ad_passthrough_metrics: []
    ad_reporting__keyword_passthrough_metrics: []
    ad_reporting__search_passthrough_metrics: []
    "dbt_date:time_zone": "America/Los_Angeles"

### Package versions

packages:
  - package: fivetran/apple_search_ads
    version: [">=0.2.0", "<0.3.0"]

  - package: fivetran/snapchat_ads
    version: [">=0.5.0", "<0.6.0"]
    
  - package: fivetran/facebook_ads
    version: [">=0.6.0", "<0.7.0"]

  - package: fivetran/google_ads
    version: [">=0.9.0", "<0.10.0"]

  - package: fivetran/pinterest
    version: [">=0.9.0", "<0.10.0"]

  - package: fivetran/linkedin
    version: [">=0.7.0", "<0.8.0"]

  - package: fivetran/microsoft_ads
    version: [">=0.6.0", "<0.7.0"]
    
  - package: fivetran/tiktok_ads
    version: [">=0.4.0", "<0.5.0"]

  - package: fivetran/twitter_ads
    version: [">=0.6.0", "<0.7.0"]

  - package: fivetran/amazon_ads
    version: [">=0.2.0", "<0.3.0"]

  - package: fivetran/reddit_ads
    version: [">=0.1.0", "<0.2.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.6.5

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by raphaelvarieras** [comment]
I see this is currently a p4 ticket - does that mean you recommend I disable the package and disable all my dependencies on it for now?

**Comment by fivetran-joemarkiewicz** [comment]
I apologize, but I didn't seem to close this after merging and releasing the update. This was live in the `v1.6.1` release of the Ad Reporting package.

Closing out this issue and thank you @Jstein77 for your help in opening the PR and addressing the issue.
