### ISSUE TITLE
Increase fivetran/google_ads version range

### ISSUE THREAD

**Issue by ben-ole** [fivetran/dbt_ad_reporting#11]
The latest version of fivetran/google_ads is `0.2.0`. This version is not supported by fivetran/ad_reporting. Any plans to do so?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @ben-ole thanks for calling this out! 

Yes, we have plans to integrate the latest version of goolge_ads (as well as the other recent releases of the ads package). We are currently working to get the most recent release of the `facebook_ads_creative_history` package on the dbt hub. Once we are able to do so, we will cut a new release of the dbt_ad_reporting package! 

I will respond back here once the new version is available.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @ben-ole! The most recent release of the ad_reporting package now supports fivetran/google_ads `[">=0.2.0", "<0.3.0"]` and also includes other features such as snapchat_ads reporting and Databricks compatibility!

The dbt_ad_reporting `v0.2.1` should be live on the dbt hub later today. Closing this Issue as it has been resolved in the most recent release.
