### ISSUE TITLE
FEATURE - Enable users to select from google's Criteria or URL ad adapters

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_ad_reporting#16]
@DylanBaker can you work on adding this variable?  

Note - this may change depending on the strategy taken w/ this open issue: https://github.com/fivetran/dbt_google_ads/issues/7

**Comment by fivetran-joemarkiewicz** [comment]
This feature is no longer possible to add with the sunsetting of AdWords and the new GoogleAds API for our connector. As such, I will close this FR.
