### ISSUE TITLE
FEATURE - inclusion of aid/oid from ad reporting platforms into ad_reporting models

### ISSUE THREAD

**Issue by heidi-trimble** [fivetran/dbt_ad_reporting#24]
**Are you a Fivetran customer?** 

Heidi Trimble, Manager - Marketing Analytics Engineering, Pluralsight

**Is your feature request related to a problem? Please describe.**

We need the Salesforce AID / OID values form the destination URLS to link Ad Performance from the Platforms back to our Salesforce Campaign and CampaignMember data

**Describe the solution you'd like**
 
I's like the AID to be included in the ad_reporting table and included as part of the level of aggregation of ad perfomance metrics. Where applicable the OID should also be surfaced in ad_reporting

**Describe alternatives you've considered**
 
Obtaining this data via other data integration

**Additional context**

AID is the Acquisition Campaign ID, OID is the Offer/Content Campaign ID. Both identifiers are sourced from Salesforce and embedded in the destination URL and included in the Ad Performance data from each platform.

**Please indicate the level of urgency and business impact of this request** 

Critical - although we have the code written and will be forking and modifying to meet the immediate need.

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
We have the code for 5 or the 7 available ad platforms; Google, Microsoft, Facebook, Twitter, and LinkedIn.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @heidi-trimble just wanted to post back here if you were able to extract the AID/OID values from the URLs provided in the based platform reports.

I still am not entirely sure what the behavior of these values is and would be happy to discuss more with you if you are interested.

**Comment by fivetran-joemarkiewicz** [comment]
HI @heidi-trimble I am going to close this ticket as it has been stale for a while.

If you would like to continue to discussion, I would encourage opening a new feature request and we may collaborate based off the latest version of the package. Thanks!
