### ISSUE TITLE
FEATURE - include account_name and account_id in the stg_facebook_ads model 

### ISSUE THREAD

**Issue by bnealdefero** [fivetran/dbt_ad_reporting#25]
**Are you a Fivetran customer?** 
Yes.. Billy Neal, Sr. Director of Development

**Is your feature request related to a problem? Please describe.**
No problems, just a feature request. 

**Describe the solution you'd like**
include account_name and account_id in the stg_facebook_ads model so it rolls up to the ad_reporting table

**Describe alternatives you've considered**
I can run this locally by directly modifying the package file models/stg_facebook-ads.sql

**Additional context**

**Please indicate the level of urgency and business impact of this request** 
Somewhat urgent as it is holding up some account level reporting we are trying to surface.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ x] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @bnealdefero thanks so much for opening this issue and chatting with me during our office hours. It was great getting to meet you!

After our chat, I think this would be feasible to include in a future update to this package. We will be starting a new sprint come next Wednesday and someone from our team will be able to take it from there. We will post back here with more details then. 

Thanks!

**Comment by fivetran-jamie** [comment]
hey there! this is included in [v0.4.1](https://github.com/fivetran/dbt_ad_reporting/releases/tag/v0.4.1) of the package
