### ISSUE TITLE
In which dbt_project.yml do we need to make the changes as stated in the documentation?

### ISSUE THREAD

**Issue by teja-goud-kandula** [fivetran/dbt_ad_reporting#48]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I am trying to setup the dbt package ad_reporting that is created by Fivetran. While making changes to the dbt_project.yml it is  confusing, to which dbt_project.yml file do I need to make the changes? Can the documentation be updated with those details please. 

### Describe alternatives you've considered

Nothing

### Are you interested in contributing this feature?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

Nothing

**Comment by fivetran-joemarkiewicz** [comment]
Hi @teja-goud-kandula when using dbt packages you can make all the variable configurations in your root `dbt_project.yml`. You won't make any adjustment to the files within the dbt package. 

I hope this is helpful and we can make the documentation more clear to explicitly identify the changes are made in your root project file.

**Comment by teja-goud-kandula** [comment]
Hi @fivetran-joemarkiewicz , let's assume we have only Google and Facebook ads. The Google ads connector is set up using google_ads  ( but not adwords). In this scenario I need to turn off all the packages except Facebook and Google ads. Need to make sure that only these 2 packages run and need to point the source database for these to FIVETRAN_DB. This is the change that I am trying to do. Can you suggest me, what are the changes and where these changes needs to be done?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @teja-goud-kandula all of these changes should be listed within our [configuration](https://github.com/fivetran/dbt_ad_reporting#configuration) section of the README and the variable configurations will be added in your root dbt_project.yml (the dbt_project.yml in your dbt project, not the packages). To achieve this result you will add the following variables to your `dbt_project.yml`:

```yml
# dbt_project.yml

vars:
  # Set the database and schema for where your facebook and google data is located.
  facebook_ads_schema: facebook_ads # you may need to change this to be the schema where you facebook ads data is
  facebook_ads_database: FIVETRAN_DB 
  google_ads_schema: google_ads # you may need to change this to be the schema where you google ads data is
  google_ads_database: FIVETRAN_DB 

  # Define the google ads API type
  api_source: google_ads  ## adwords by default and is case sensitive!

  # I disabled all ad connectors that you do not want to use.
  ad_reporting__pinterest_enabled: False
  ad_reporting__microsoft_ads_enabled: False
  ad_reporting__linkedin_ads_enabled: False
  ad_reporting__twitter_ads_enabled: False
  ad_reporting__snapchat_ads_enabled: False
  ad_reporting__tiktok_ads_enabled: False

models:
  # disable both pinterest models if not using pinterest ads
  pinterest:
    enabled: false
  pinterest_source:
    enabled: false
  
  # disable both microsoft ads models if not using microsoft ads
  microsoft_ads:
    enabled: false
  microsoft_ads_source:
    enabled: false
  
  # disable both linkedin ads models if not using linkedin ads
  linkedin:
    enabled: false
  linkedin_source:
    enabled: false
  
  # disable both twitter ads models if not using twitter ads
  twitter_ads:
    enabled: false
  twitter_ads_source:
    enabled: false
  
  # disable both snapchat ads models if not using snapchat ads
  snapchat_ads:
    enabled: false
  snapchat_ads_source:
    enabled: false
  
  # disable both tiktok ads models if not using tiktok ads
  tiktok_ads:
    enabled: false
  tiktok_ads_source:
    enabled: false

**Comment by teja-goud-kandula** [comment]
Hi @fivetran-joemarkiewicz ,

It worked. I am able to set up the ad reporting. 

Thanks for the quick response.
