### ISSUE TITLE
[Docs] Update Ad Reporting Info about Google Ads API and Deprecated AdWords API

### ISSUE THREAD

**Issue by MitchellRLayton** [fivetran/dbt_ad_reporting#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

This section ([https://github.com/fivetran/dbt_ad_reporting/tree/v0.7.0/#google-ads-and-adwords-api-configuration](https://github.com/fivetran/dbt_ad_reporting/tree/v0.7.0/#google-ads-and-adwords-api-configuration)) needs updated to reflect the changes to Google's APIs.

### Relevant error log or model output

```shell
N/A
```

### Expected behavior

Google Ads API is the only API to worry about.

### dbt Project configurations

N/A

### Package versions

N/A

### What database are you using dbt with?

other (mention it in "Additional Context")

### dbt Version

N/A

### Additional Context

[https://fivetran.slack.com/archives/CAGK0BU0Z/p1653080137055409](https://fivetran.slack.com/archives/CAGK0BU0Z/p1653080137055409)

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
The recent release of `v0.8.0` of this package addresses this issue.
