### ISSUE TITLE
FEATURE - Include a "revenue" metric to the Ad_Reporting model

### ISSUE THREAD

**Issue by MitchellRLayton** [fivetran/dbt_ad_reporting#52]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Customers have been asking about a specific **revenue** metric for each of the ad reporting connectors they leverage. I realize we add different query granularity columns such campaign name/ID, ad group name/ID, account name/ID — so we'd really just need a metric in addition to the already present spend, clicks, impressions which could capture the return on ad spend (i.e. revenue) somehow. 

_Quote from customer:_
> As you know with each marketing channel we're looking for some pretty simple metrics (e.g. spend, impressions, clicks on ads). In addition to some of those, we really need to start pulling in revenue per campaign from each of the connectors we leverage.

Context: I have worked with some existing Powered by Fivetran customers who does not use dbt in their data stack and so they have a bunch of in-house Python scripts which run the transformations to achieve cross-platform analysis for spend, clicks, impressions, etc. I think having revenue would influence this customer (and future ones) to simply setup Fivetran Transformations and leverage Data Models. 

### Describe alternatives you've considered

Going to work with customer to create the report configurations and/or metadata tables which have a revenue-like metric to pull into their existing ELT pipelines via Python.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

### Anything else?

N/A

**Comment by fivetran-reneeli** [comment]
Hey Mitchell! Thanks for creating this!

We think revenue is a logical next step to the existing conversion metrics from ad platforms. The thing is however ads don't typically come with revenue data; instead that tends to be pulled from another area of the tech stack like Square. This way it keeps revenue where it occurs, often at the POS tool. The tricky thing about adding revenue directly to ad platforms is that customers may choose to attribute revenue back to ads differently (first touch, time decay, etc) and gets even more complex considering cross-channel attribution. In other words metrics like revenue per ad and ROAS are different for each customer. 

This is a great point to bring up though! We're actually working on our Ad Reporting package on the upcoming sprint so we'd love to get your thoughts on how to set up our packages to help customers bring in these metrics more seamlessly. Let me know if you have additional context to share!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for chiming in here @fivetran-reneeli and for the great question @MitchellRLayton!

@MitchellRLayton our team just finished a major update to our Ad Reporting package (see our [v1.0.0](https://github.com/fivetran/dbt_ad_reporting/releases/tag/v1.0.0) release for more details). This release covers significantly more reporting possibilities for our customers. It even allows for custom metrics (including metrics crucial in rev calculations) to be passed through to the individual platform level (see the output of the Google Ads models for example). A user could then use the data from the reports of our package to calculate revenue on top of our package.

As @fivetran-reneeli stated above, ads data doesn't typically come enriched with revenue data. However, users should be able to use our package in combination with their own models to join and enrich the data to extract revenue metrics. As this type of modeling is not best served within our packages (and rather on the user end) we will close out this ticket.

We will still take into account how we may better enrich the ads data (maybe with other data sources) for a future enhancement to the package. Thank you!
