### ISSUE TITLE
[Feature] Allow Google PMAX campaign clicks,spend,Impressions through package 

### ISSUE THREAD

**Issue by Elvie-JackRockett** [fivetran/dbt_ad_reporting#56]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Because of the required joins detailed in this package, the requirement for ad group level details means that the new Google Pmax campaigns are lost early on in this model and consequently don't make it to the reporting layer.

because of the nature of this new ML assisted campaign type, it doesn't produce data in all the api tables the same way other campaign types have in the past.

Can we develop a parameter on setup to not use the ad group level details and keep to campaign level only?

### Describe alternatives you've considered

short of starting an attempt to re-designing the package from scratch to fit our business need, we haven't explored any other options.

We have some time booked in with Joe already to discuss this issue

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @Elvie-JackRockett thank you for opening this issue. I have hear others talking about the new PMAX campaigns in Google and how they are not being reflected in the end model.

I haven't done too much investigation into PMAX campaigns, but we just cut a new release of the Ad Reporting package that I believe may account for them! Would you be able to install the latest version of the package and explore the campaign or ad group level report. I think the PMAX records would be included within!
```yml
packages:
  - package: fivetran/ad_reporting
    version: [">=1.0.0", "<1.1.0"]
```
Let me know if this works!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for opening this issue @Elvie-JackRockett. From our conversation last week we found that Google PMAX campaigns are included in the `ad_reporting__campaign_report` model within the latest `v1.0.0` version of the Ad Reporting package.

As the upgrade addressed this, I will close this issue.
