### ISSUE TITLE
[Bug] Incorrect documentation for LinkedIn Ads

### ISSUE THREAD

**Issue by clay-walker** [fivetran/dbt_ad_reporting#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The documentation listed [here](https://hub.getdbt.com/fivetran/ad_reporting/latest/) indicates that the user must include the "linkedin_schema" and "linkedin_database" vars in dbt_project.dbt. 

The correct vars are:

linkedin_ads_schema
linkedin_ads_database

### Expected behavior

Expected the ad models to build successfully

### dbt Project configurations

vars:
  prod_database: analytics

  ad_reporting__apple_search_ads_enabled: False # by default this is assumed to be True
  ad_reporting__pinterest_ads_enabled: False # by default this is assumed to be True
  ad_reporting__twitter_ads_enabled: False # by default this is assumed to be True
  ad_reporting__facebook_ads_enabled: False # by default this is assumed to be True
  ad_reporting__snapchat_ads_enabled: False # by default this is assumed to be True
  ad_reporting__tiktok_ads_enabled: False # by default this is assumed to be True

  linkedin_schema: linkedin_ads 
  linkedin_database: source_raw
  
  google_ads_schema: google_ads
  google_ads_database: source_raw 

  microsoft_ads_schema: bingads
  microsoft_ads_database: source_raw

### Package versions

packages:
  - package: fivetran/salesforce_formula_utils
    version: 0.6.4
    
  - package: calogica/dbt_date
    version: 0.5.7

  - package: fivetran/ad_reporting
    version: [">=1.0.0", "<1.1.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.0.1

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @clay-walker thanks so much for opening this issue!

You are correct that the documentation for Linkedin ads schema and database variables is inaccurate and something we should update. I noticed you mention you are open to contributing and creating a PR to address this issue. If you are still open to this, we would be happy to review your PR and incorporate your contribution in our next release!

Let me know if you have any questions on the PR process. 🙏

**Comment by fivetran-joemarkiewicz** [comment]
Hi @clay-walker we are planning to release a new patch version of ad_reporting `v1.0.1` tomorrow. If you would like your contribution to be included I would recommend opening a PR prior to tomorrow afternoon.

Otherwise, we can fold in the change along with our PR #57. Let me know if you have any questions 😄

**Comment by clay-walker** [comment]
Hey @fivetran-joemarkiewicz I'd love to contribute. Any guidelines I should be aware of before submitting a PR?

**Comment by clay-walker** [comment]
I cloned the repo locally, created a branch and staged my changes. Getting a 403 forbidden when I try to push to the repo. 🙃

**Comment by fivetran-joemarkiewicz** [comment]
Hey @clay-walker you will need to fork the repo in order to open a PR against it. I would recommend checking out [this discourse post](https://discourse.getdbt.com/t/contributing-to-an-external-dbt-package/657) on how to best contribute. Thanks!

**Comment by fivetran-joemarkiewicz** [comment]
This has been addressed within the latest release of the package.
