### ISSUE TITLE
[Bug] Inconsistency in default value for var `twitter_ads__using_keywords`

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_ad_reporting#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The default value for `twitter_ads__using_keywords` is False in some places and True in others. This runs fine if a value for the variable is provided but causes an error if no value is provided since the defaults conflict. 

According to the [README](https://github.com/fivetran/dbt_ad_reporting/blob/main/README.md#enabledisable-specific-reports-within-platforms), the defaults should all be True, but making them all False would also work I assume. 

See from `int_ad_reporting__keyword_report`:
https://github.com/fivetran/dbt_ad_reporting/blob/2146d06da804047427cf336e19ce122e7b1dac6e/models/intermediate/int_ad_reporting__keyword_report.sql#L1
vs

https://github.com/fivetran/dbt_ad_reporting/blob/2146d06da804047427cf336e19ce122e7b1dac6e/models/intermediate/int_ad_reporting__keyword_report.sql#L74
and from`ad_reporting__keyword_report`:
https://github.com/fivetran/dbt_ad_reporting/blob/2146d06da804047427cf336e19ce122e7b1dac6e/models/ad_reporting__keyword_report.sql#L1

### Expected behavior

Runs without errors if no value is provided for `twitter_ads__using_keywords`.

### dbt Project configurations

Value for `twitter_ads__using_keywords` deliberately not provided.

### Package versions

packages:
  - package: fivetran/ad_reporting
    version: [">=1.0.0", "<1.1.0"]

### What database are you using dbt with?

bigquery

### dbt Version

1.3.0

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-sheringuyen** [comment]
Resolved with release 1.0.3
