### ISSUE TITLE
[Bug] Error in int_ad_reporting__url_report.sql

### ISSUE THREAD

**Issue by bruceconklin** [fivetran/dbt_ad_reporting#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In this intermediate model: https://github.com/fivetran/dbt_ad_reporting/blob/v1.2.0/models/intermediate/int_ad_reporting__url_report.sql

Snapchat_ads contains a series of field mappings that are set to null. This is preventing these fields from populating in the model output.
`snapchat_ads as (

    {{ get_query(
        platform='snapchat_ads', 
        report_type='url', 
        field_mapping={
                'account_id': 'ad_account_id',
                'account_name': 'ad_account_name',
                'campaign_id': 'null',
                'campaign_name': 'null',
                'ad_group_id': 'null',
                'ad_group_name': 'null',
                'clicks':'swipes'
            },
        relation=ref('snapchat_ads__url_report')
    ) }}
), `

I believe this is an error as other mappings do not contain null values.

### Expected behavior

I expect these to map to the correct field in the source table

### dbt Project configurations

N/A

### Package versions

N/A

### What database are you using dbt with?

other (mention it in "Additional Context")

### dbt Version

N/A

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by dumkydewilde** [comment]
Thanks for filing this @bruceconklin. This also relates to these columns not being available in the `snapchat_ads` package. I've created [a PR to add those columns](https://github.com/fivetran/dbt_snapchat_ads/pull/14) there, so they can also be used in the `ad_reporting` package.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this @bruceconklin and for chiming in @dumkydewilde!

I chatted with @dumkydewilde in the snapchat ads PR and will move forward with reviewing and integrating these PRs. Stay tuned as we work through these.

**Comment by fivetran-joemarkiewicz** [comment]
@bruceconklin and @dumkydewilde I just wanted to provide an update that I have reviewed and approved the two mentioned PRs! I am kicking off our internal release process. You can most likely expect these to be merged and released by early next week.

**Comment by fivetran-joemarkiewicz** [comment]
FYI the above mentioned PRs have been approved and merged into the latest release of the Snapchat and Ad reporting packages.

As such, I will close out this issue. Please feel free to reopen if the issue still persists on your end.
